### PR TITLE
Stupid fast build script for piglins

### PR DESCRIPTION
**Pull request by MaxBr5**
<pre>I made the build script stupid fast and one that
made smaller jars too.  A piglin would love it.</pre>

### CODE REVIEW

**Comment by FionaTheMortal** [comment]
I think that debugging information for stacktraces and such can be very helpful so I don't think that the reduced file size is worth turning that off

**Comment by MaxBr5** [comment]
<pre>
The stacktraces are:

Fabric Loom: 0.8.21
Using project based jar storage

> Task :compileJava
warning: Supported source version 'RELEASE_8' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '16'
warning: Supported source version 'RELEASE_8' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '16'
C:\Users\MaxBr\better-biome-blend\src\main\java\fionathemortal\betterbiomeblend\mixin\MixinClientWorld.java:115: warning: @Overwrite is missing javadoc comment
    getColor(BlockPos blockPosIn, ColorResolver colorResolverIn)
    ^
3 warnings
unknown invokedynamic bsm: java/lang/invoke/StringConcatFactory/makeConcatWithConstants(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite; (tag=6 iif=false)

> Task :remapSourcesJar
:remapping sources

BUILD SUCCESSFUL in 46s
6 actionable tasks: 6 executed
</pre>

**Comment by MaxBr5** [comment]
<pre>
And for 1.16:
===

> Configure project :
Fabric Loom: 0.6.59 Build(release #59)

> Task :compileJava
C:\Users\MaxBr\better-biome-blend\src\main\java\fionathemortal\betterbiomeblend\mixin\MixinClientWorld.java:114: warning: @Overwrite is missing javadoc comment
    getColor(BlockPos blockPosIn, ColorResolver colorResolverIn)
    ^
1 warning

> Task :remapSourcesJar
:remapping sources
<pre>

**Comment by MaxBr5** [comment]
<pre>I know build system magic.</pre>

**Comment by MaxBr5** [comment]
<pre>Well, you could delete line 3 for debug
input and put it back for faster builds.</pre>

**Pull request closed without merging**
