### PR TITLE
Update gradle to 7.1.1 in 1.12

### PR DESCRIPTION
**Pull request by MaxBr5**
Make Fiona the Mortal's better biome blend for 1.12 compatible with all versions java 8 and newer by just updation gradle.

### CODE REVIEW

**Comment by FionaTheMortal** [comment]
I'm having issues with this one. Have you tested it?

**Comment by MaxBr5** [comment]
<pre>Yes and it works perfectly fine.

**Comment by MaxBr5** [comment]
<pre>Are you mocking my spelling mistake of updating?

**Comment by FionaTheMortal** [comment]
No but isn't forge gradle incompatible with gradle 7?
I don't wanna do build systems I just want them to work and get out of my way.

**Comment by MaxBr5** [comment]
Oh, it does not work.

**Comment by MaxBr5** [comment]
Oh, I hate forge.

**Pull request closed without merging**
